"""Helpers for attaching deterministic options analytics to analyst nodes.

The existing TradingAgents graph remains intact. These helpers only augment the
stock/futures-oriented analyst tools when the requested instrument is one of
Alan's SHFE metals option products.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from tradingagents.agents.utils.options_tools import (
    get_option_research_pack,
    get_option_strategy_selection,
    get_option_trade_context,
)
from tradingagents.options.data_loader import normalize_product

_OPTIONS_PRODUCTS = {"CU", "AU", "AG", "AL", "ZN", "NI", "PB", "SN", "AO"}

_ROLE_LENS = {
    "market": "underlying trend, realized volatility, technical context, futures anchor, and option-implied volatility.",
    "fundamentals": "inventory, warehouse receipts, term structure, macro anchors, and volatility regime drivers.",
    "news": "event risks, policy/macroeconomic shocks, supply disruptions, and tail-demand repricing for IV/skew.",
}


def is_options_analytics_symbol(symbol: str | None) -> bool:
    """Return True when a symbol can be analyzed by the SHFE options core."""
    if not symbol:
        return False
    return normalize_product(symbol) in _OPTIONS_PRODUCTS


def augment_tools_for_options(
    tools: Sequence[Any],
    symbol: str | None,
    analyst_role: str,
) -> list[Any]:
    """Add options analytics tools for supported SHFE metals symbols.

    The compact context tool is added to every analyst role. Market analysts
    receive only compact LLM-facing tools by default; heavy audit/report/scenario
    tools remain callable directly by humans/tests but are not bound to the live
    analyst graph unless explicitly reintroduced in a debug path.
    """
    augmented = list(tools)
    if not is_options_analytics_symbol(symbol):
        return augmented

    if get_option_trade_context not in augmented:
        augmented.append(get_option_trade_context)

    if analyst_role == "market":
        for tool in (
            get_option_strategy_selection,
            get_option_research_pack,
        ):
            if tool not in augmented:
                augmented.append(tool)
    return augmented


def options_analyst_instruction(symbol: str | None, analyst_role: str) -> str:
    """Return volatility-first prompt guidance for SHFE options instruments."""
    if not is_options_analytics_symbol(symbol):
        return ""

    product = normalize_product(symbol)
    lens = _ROLE_LENS.get(analyst_role, "volatility regime, option positioning, and risk scenarios.")
    return (
        f"\n\nSHFE options analytics mode is active for {product}. "
        "Use get_option_trade_context first to obtain deterministic option analytics. "
        "Keep the analysis volatility-first: focus on IV level, volatility surface, term structure, skew, PCR, walls, gamma flip, and Greeks/risk scenarios. "
        "Do not recalculate IV/Greeks/GEX/DEX in the LLM; treat the tool JSON as the source of truth. "
        "Default price basis is option close + futures close, with r = 1.5%; use settlement only for explicit settlement/risk-control requests. "
        "Market analyst tools are compact by default to avoid full-graph timeouts: use get_option_strategy_selection for deterministic ranking and get_option_research_pack for a unified side-effect-free research pack summary. "
        "Only request detail_level='full' in explicit debug/audit contexts; normal live debate should stay on compact payloads. "
        "Feishu/Hermes delivery artifacts are side-effect-free and should be generated by the CLI/workflow outside the live analyst graph. "
        "GEX/DEX are exchange-OI scenario/concentration metrics because dealer position is unknown. "
        f"For this analyst role, emphasize {lens}"
    )


def options_researcher_instruction(symbol: str | None, stance: str) -> str:
    """Return bull/bear debate guidance for volatility-first option research."""
    if not is_options_analytics_symbol(symbol):
        return ""

    product = normalize_product(symbol)
    stance_word = "rising" if stance == "bull" else "falling"
    counter_word = "falling" if stance == "bull" else "rising"
    return (
        f"\n\nSHFE options research mode is active for {product}. Reframe the debate around implied volatility, not only outright direction. "
        "For each horizon, explicitly compare the probability of implied volatility rising versus falling: 5-day, 20-day, and 40-day. Use the explicit rise/fall framing so the trader can compare paths. "
        f"As the {stance} researcher, make the strongest evidence-based case for {stance_word} volatility where justified, while acknowledging conditions that would favor {counter_word} volatility. "
        "Anchor the argument in the analyst reports' option context: ATM IV, term structure, skew, PCR, walls, gamma flip, event risk, and inventory/macro drivers. "
        "Do not recalculate IV/Greeks/GEX/DEX; treat deterministic option analytics from the tools/reports as source-of-truth inputs. "
        "End with a concise horizon table: 5-day / 20-day / 40-day, IV-up probability, IV-down probability, key catalysts, and preferred option structure bias."
    )


def options_trader_instruction(symbol: str | None) -> str:
    """Return trader guidance for options mode."""
    if not is_options_analytics_symbol(symbol):
        return ""

    product = normalize_product(symbol)
    return (
        f"\n\nSHFE options trading mode is active for {product}. Before proposing any option structure, first state your volatility view. "
        "Synthesize the previous analyst evidence plus the bull and bear debate about whether implied volatility is more likely to rise or fall over the 5-day, 20-day, and 40-day horizons; explicitly reference volatility surface, skew, and term structure when available. "
        "Only after that volatility view should you propose option structures. Prefer defined-risk structures unless the evidence and liquidity justify otherwise. Use get_option_strategy_selection when you need a deterministic strategy ranking before choosing a final structure. "
        "When an option structure is proposed, include a structured option strategy object with legs, expiry, strike, side, quantity, debit/credit, max loss, max profit, breakeven, Greeks snapshot, liquidity filter, contract multiplier, cash premium/max loss, bid/ask execution prices, slippage, execution liquidity score, credit execution metrics for credit structures, margin required, risk budget pass/fail, and no-trade reasons. "
        "Tie every structure to the vol view, directional view, expiry, strike area, liquidity, Greeks, cash premium/max loss, bid/ask feasibility, slippage, execution liquidity, executable credit/risk ratio when applicable, margin required, risk budget pass/fail, and no-trade conditions. "
        "Do not recalculate IV/Greeks/GEX/DEX; use the prior deterministic analytics as source-of-truth inputs. "
        "Default basis remains option close + futures close, r = 1.5%, with GEX/DEX treated only as exchange-OI scenario metrics."
    )


def options_research_manager_instruction(symbol: str | None) -> str:
    """Return research-manager guidance for preserving the volatility debate handoff."""
    if not is_options_analytics_symbol(symbol):
        return ""

    product = normalize_product(symbol)
    return (
        f"\n\nSHFE options research-manager mode is active for {product}. Your investment plan must preserve a Volatility Debate Summary for the trader. "
        "Compare the bull and bear arguments on the probability of implied volatility rising versus falling across 5-day, 20-day, and 40-day horizons. "
        "State which horizon has the clearest edge, which horizons are balanced, and what catalysts would flip the view. "
        "The trader must first state a volatility view before selecting option structures, so make this handoff explicit."
    )


def options_risk_debator_instruction(symbol: str | None, risk_role: str) -> str:
    """Return options-mode guidance for aggressive/neutral/conservative risk analysts."""
    if not is_options_analytics_symbol(symbol):
        return ""

    product = normalize_product(symbol)
    role_lens = {
        "aggressive": "identify where the reward justifies taking defined option risk, but do not ignore Greeks or liquidity.",
        "neutral": "balance upside/downside by translating the trader's vol view into scenario and sizing constraints.",
        "conservative": "stress the failure modes, capital protection, and no-trade filters before approving risk.",
    }.get(risk_role, "evaluate the option structure risk controls.")
    return (
        f"\n\nSHFE options risk mode is active for {product}. Evaluate the trader's proposed option structure through an options-risk lens: {role_lens} "
        "Explicitly cover Greeks: delta, gamma, theta, and vega; discuss gamma/theta trade-off, volatility surface, skew, term structure, and vega exposure under 5-day, 20-day, and 40-day volatility paths. "
        "Use the trader's structured strategy / scenario PnL matrix when present: cite the worst scenario, best scenario, T+5 and T+20 time-decay cases, IV up/down sensitivity, max loss consistency, and breakeven proximity. "
        "Evaluate contract multiplier conversion and cash risk fields: net premium cash, max loss cash, scenario PnL cash, underlying notional, executable credit and execution-adjusted max loss for credit structures, margin required, risk budget pass/fail, and risk budget utilization. "
        "Check liquidity, bid/ask feasibility, slippage, execution liquidity score, executable credit/wing-width ratio where applicable, open interest concentration, expiry risk, margin, max loss, and whether the risk budget can absorb margin required, premium decay, or stress moves. "
        "List concrete no-trade conditions such as poor liquidity, wide bid/ask, excessive slippage, weak execution liquidity, insufficient executable credit, excessive theta bleed, unstable gamma near expiry, margin/max loss beyond budget, unacceptable scenario PnL, adverse breakeven proximity, or invalidated volatility view. "
        "Remember dealer position is unknown; GEX/DEX from exchange OI are scenario/concentration metrics, not verified dealer inventory."
    )


def options_portfolio_instruction(symbol: str | None) -> str:
    """Return final portfolio-manager guidance for options mode."""
    if not is_options_analytics_symbol(symbol):
        return ""

    product = normalize_product(symbol)
    return (
        f"\n\nSHFE options portfolio mode is active for {product}. The final decision must include a Scenario PnL Assessment, an Options Risk Assessment, and No-Trade Conditions. "
        "Before approving any trade, check the scenario PnL matrix: worst scenario, best scenario, T+5 and T+20 time-decay cases, IV up/down sensitivity, max loss consistency, and breakeven proximity. "
        "When get_option_strategy_selection is available, use its portfolio_summary to compare the selected strategy against alternative candidates: selected risk-budget utilization, total tradable-candidate margin/max-loss, highest-margin structure, lowest-max-loss structure, watchlist, and no-trade rows. "
        "When historical replay is present, inspect performance_summary for win/lose/flat distribution, win rate, average/final PnL cash, max drawdown, PnL path, and IV-regime buckets before relying on the post-trade outcome. "
        "Verify contract multiplier conversion from option-price points into cash: net premium cash, max loss cash, scenario PnL cash, underlying notional, executable credit and execution-adjusted max loss for credit structures, margin required, risk budget pass/fail, and risk budget utilization. "
        "Then check Greeks, delta/gamma/theta/vega exposure, liquidity, bid/ask, slippage, execution liquidity score, executable credit/wing-width ratio where applicable, expiry risk, margin, max loss, and risk budget. "
        "Tie the position size to maximum premium at risk or defined max loss; avoid naked short gamma unless explicitly justified by liquidity, margin, and stress scenarios. "
        "State no-trade conditions clearly: poor liquidity, wide bid/ask, excessive slippage, weak execution liquidity, insufficient executable credit, excessive theta bleed, unstable gamma near expiry, margin/max loss beyond risk budget, unacceptable scenario PnL, adverse breakeven proximity, or a broken volatility view. "
        "Dealer position is unknown, so GEX/DEX must remain exchange-OI scenario metrics, not proof of dealer inventory."
    )
